name: sistemium_sync_flutter
version: 2.5.10
environment:
  sdk: ">=3.9.2"
  flutter: ">=3.35.5"
dependencies:
  flutter:
    sdk: flutter
  http: 1.5.0
  sqlite_async: 0.12.1
  path_provider: 2.1.5
  objectid: 4.0.1
  collection: 1.19.1
  path: 1.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
executables:
  sync_generator: